### ISSUE TITLE
csv_files folder

### ISSUE THREAD

**Issue by priyacshah** [Abhinav1004/Distracted-Driver-Detection#15]
Can you please mention how did you create train.csv and test.csv files ?

**Comment by Abhinav1004** [comment]
The code is a part of CNN scratch 1 https://github.com/Abhinav1004/Distracted-Driver-Detection/blob/master/Distracted%20Driver%20Detection%20CNN%20Scratch.ipynb 
It is done so as to do access train and test csv files as per requirements.
