### ISSUE TITLE
Error in Distracted-Driver-Detection-vgg16

### ISSUE THREAD

**Issue by kalai86** [Abhinav1004/Distracted-Driver-Detection#3]
HI,

 i got error like

InternalError: Could not synchronize CUDA stream: CUDA_ERROR_LAUNCH_TIMEOUT: the launch timed out and was terminated

pls suggest me how to solve it

**Comment by Abhinav1004** [comment]
Please include the screensho,so that i can help you with,the error does not comes normally unless you have sufficient ram 8gb minimum
