### ISSUE TITLE
Prediction Error

### ISSUE THREAD

**Issue by kalai86** [Abhinav1004/Distracted-Driver-Detection#4]
i have like

KeyError                                  Traceback (most recent call last)
<ipython-input-10-7473573b0e7f> in <module>
      6 
      7 for i in range(data_test.shape[0]):
----> 8     new_name = data_test.iloc[i,0].split("/")[-1].split(".")[0]+"_"+info[data_test.iloc[i,1]]+".jpg"
      9     shutil.copy(data_test.iloc[i,0],os.path.join(PREDICT_DIR,new_name))
     10 

KeyError: 'C0'

thanks
kalai

**Comment by Abhinav1004** [comment]
have you executed the training files completely before running this prediction file .?the error will come only because of this
